# Mathread Merge

In [175]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from scipy import stats
import statsmodels.formula.api as sm

df1 = pd.read_csv("Math 08-09.csv")
df1['Year'] = np.array(2008)
df1.rename(columns = {"leanm08":"Name of reporting district"}, inplace=True)
df2 = pd.read_csv("Math 09-10.csv")
df2['Year'] = np.array(2009)
df2.rename(columns = {"leanm09":"Name of reporting district"}, inplace=True)
df3 = pd.read_csv("Math 10-11.csv")
df3['Year'] = np.array(2010)
df3.rename(columns = {"leanm10":"Name of reporting district"}, inplace=True)
df4 = pd.read_csv("Math 11-12.csv")
df4['Year'] = np.array(2011)
df4.rename(columns = {"leanm11":"Name of reporting district"}, inplace=True)
math = df1.append([df2, df3, df4])

read1 = pd.read_csv("Reading 08-09.csv")
read1['Year'] = np.array(2008)
read1.rename(columns = {"leanm08":"Name of reporting district"}, inplace=True)
read2 = pd.read_csv("Reading 09-10.csv")
read2['Year'] = np.array(2009)
read2.rename(columns = {"leanm09":"Name of reporting district"}, inplace=True)
read3 = pd.read_csv("Reading 10-11.csv")
read3['Year'] = np.array(2010)
read3.rename(columns = {"leanm10":"Name of reporting district"}, inplace=True)
read4 = pd.read_csv("Reading 11-12.csv")
read4['Year'] = np.array(2011)
read4.rename(columns = {"leanm11":"Name of reporting district"}, inplace=True)
read = read1.append([read2, read3, read4])

In [157]:
# merge math and reading performance indicators on Name of reporting district, State and Year 
list = ['LEAID', 'STNAM', 'Year']

mathread = pd.merge(math, read, left_on = list , right_on = list)

In [158]:
#header cleaning
mathread.rename(columns = {"STNAM": "State", "LEAID": "DISTRICT_ID", "Name of reporting district_x": 'Name of reporting district'}, inplace=True)
#mathread.columns = mathread.columns.str.replace('MTH', 'MATH_GRADE')
#mathread.columns = mathread.columns.str.replace('RLA', 'READ_GRADE')
mathread['State'] = mathread['State'].str.lower()
drop_col = ['FIPST_x', 'FIPST_y', 'Name of reporting district_y']
mathread.drop(drop_col, axis=1, inplace=True)
mathread['Name of reporting district'] = mathread['Name of reporting district'].str.lower()
mathread = mathread.replace('^[A-Z]{2}', np.nan, regex=True)
mathread = mathread.replace('n/a', np.nan)

In [159]:
mathread['Name of reporting district'] = np.where(mathread['State'] == 'california', 
                                                  mathread['Name of reporting district'].astype(str)+ str(' school district'), 
                                                  mathread['Name of reporting district'])

mathread['Name of reporting district'] = np.where(mathread['State'] == 'alabama', 
                                                  mathread['Name of reporting district'].astype(str)+ str(' school district'), 
                                                  mathread['Name of reporting district'])

mathread['Name of reporting district'] = np.where(mathread['State'] == 'florida', mathread['Name of reporting district'].astype(str)+ str(' county school district'), mathread['Name of reporting district'])


mathread["State"] = pd.core.strings.str_strip(mathread["State"])

In [160]:
mathread.ix[mathread["State"] == "illinois", "Name of reporting district"] = mathread.ix[mathread["State"] == "illinois", "Name of reporting district"].str.replace("sd", "school district")
mathread.ix[mathread["State"] == "pennsylvania", "Name of reporting district"] = mathread.ix[mathread["State"] == "pennsylvania", "Name of reporting district"].str.replace("city sd", "school district")
#remove double statistic
mathread.ix[mathread["State"] == "texas", "Name of reporting district"] = mathread.ix[mathread["State"] == "texas", "Name of reporting district"].str.replace("northside", "ns")
mathread.ix[mathread["State"] == "south carolina", "Name of reporting district"] = mathread.ix[mathread["State"] == "south carolina", "Name of reporting district"].str.replace("greenville 01", "greenville county school district")
mathread.ix[mathread["State"] == "tennessee", "Name of reporting district"] = mathread.ix[mathread["State"] == "tennessee", "Name of reporting district"].str.replace("memphis city schools district$", "memphis city schools")
mathread.ix[mathread["State"] == "arizona", "Name of reporting district"] = mathread.ix[mathread["State"] == "arizona", "Name of reporting district"].str.replace("district", "school district")
mathread.ix[mathread["State"] == "utah", "Name of reporting district"] = mathread.ix[mathread["State"] == "utah", "Name of reporting district"].str.replace("district", "school district")
mathread.ix[mathread["State"] == "georgia", "Name of reporting district"] = mathread.ix[mathread["State"] == "georgia", "Name of reporting district"].str.replace("county", "county school district")
mathread.ix[mathread["State"] == "alabama", "Name of reporting district"] = mathread.ix[mathread["State"] == "alabama", "Name of reporting district"].str.replace("county", "county school district")
mathread.ix[mathread["State"] == "tennessee", "Name of reporting district"] = mathread.ix[mathread["State"] == "tennessee", "Name of reporting district"].str.replace("knox county$", "knox county school district")
mathread.ix[mathread["State"] == "ohio", "Name of reporting district"] = mathread.ix[mathread["State"] == "ohio", "Name of reporting district"].str.replace("columbus city$", "columbus city school district")
mathread.ix[mathread["State"] == "tennessee", "Name of reporting district"] = mathread.ix[mathread["State"] == "tennessee", "Name of reporting district"].str.replace("shelby county$", "shelby county school district")

In [161]:
mathread.to_csv("mathread.csv", inplace = True)

# Append Fiscal Expenditure 08-11

In [162]:
df08 = pd.read_excel('100LSD_Fiscal_Tables_FY08.xlsx', header=2)
df09 = pd.read_excel('100LSD_Fiscal_Tables_FY09.xlsx', header=2)
df10 = pd.read_excel('100LSD_Fiscal_Tables_FY10.xlsx', header=2)
df11 = pd.read_excel('100LSD_Fiscal_Tables_FY11.xlsx', header=2)

In [163]:
df08.dropna(inplace = True)
df09.dropna(inplace = True)
df10.dropna(inplace = True)
df11.dropna(inplace = True)

In [164]:
df10_nospace = pd.core.strings.str_strip(df10['Name of reporting district'])
df11_nospace = pd.core.strings.str_strip(df11['Name of reporting district'])

In [165]:
df08['Year'] = np.array(2008)
df09['Year'] = np.array(2009)
df10['Year'] = np.array(2010)
df11['Year'] = np.array(2011)

In [166]:
df10.drop('Name of reporting district', axis=1, inplace=True)
df10['Name of reporting district'] = df10_nospace
df11.drop('Name of reporting district', axis=1, inplace=True)
df11['Name of reporting district'] = df11_nospace

In [167]:
cols = df10.columns.tolist()
col2 = cols[-1:] + cols[:-1]
df10 = df10[col2]
df11 = df11[col2]

In [168]:
fiscal = df08.append([df09, df10, df11])
fiscal['Name of reporting district'] = fiscal['Name of reporting district'].str.lower()
fiscal["Year"] = fiscal["Year"].astype(int)
fiscal["State"] = pd.core.strings.str_strip(fiscal["State"])
fiscal['State'] = fiscal['State'].str.lower()

In [169]:
#stripping arizona 
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 1') 
#stripping texas
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 901') 
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 902') 
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 903') 
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 904')
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 905')
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 906') 
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 907') 
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 908')
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 909')
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 910')
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 911') 
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 912') 
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 913') 
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 914') 
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 915')

fiscal.ix[fiscal["State"] == "new mexico", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "new mexico", "Name of reporting district"].str.replace("school district", "public schools")
fiscal.ix[fiscal["State"] == "maryland", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "maryland", "Name of reporting district"].str.replace("county schools", "county public schools")
fiscal.ix[fiscal["State"] == "texas", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "texas", "Name of reporting district"].str.replace("arlington independent school$", "arlington independent school district")
fiscal.ix[fiscal["State"] == "maryland", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "maryland", "Name of reporting district"].str.replace("baltimore city schools$", "baltimore city public schools")
fiscal.ix[fiscal["State"] == "ohio", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "ohio", "Name of reporting district"].str.replace("columbus city$", "columbus city school district")
fiscal.ix[fiscal["State"] == "north carolina", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "north carolina", "Name of reporting district"].str.replace("cumberland county school$", "cumberland county schools")
fiscal.ix[fiscal["State"] == "michigan", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "michigan", "Name of reporting district"].str.replace("detroit public school district$", "detroit city school district")
fiscal.ix[fiscal["State"] == "georgia", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "georgia", "Name of reporting district"].str.replace("fulton county$", "fulton county school district")
fiscal.ix[fiscal["State"] == "georgia", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "georgia", "Name of reporting district"].str.replace("fulton county³$", "fulton county school district")
fiscal.ix[fiscal["State"] == "california", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "california", "Name of reporting district"].str.replace("garden grove unified school dist$", "garden grove unified school district")
fiscal.ix[fiscal["State"] == "north carolina", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "north carolina", "Name of reporting district"].str.replace("guilford county school$", "guilford county schools")
fiscal.ix[fiscal["State"] == "hawaii", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "hawaii", "Name of reporting district"].str.replace("hawaii public schools$", "hawaii department of education")
fiscal.ix[fiscal["State"] == "wisconsin", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "wisconsin", "Name of reporting district"].str.replace("milwaukee city school district$", "milwaukee school district")
fiscal.ix[fiscal["State"] == "maryland", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "maryland", "Name of reporting district"].str.replace("montgomery county school$", "montgomery county public schools")
fiscal.ix[fiscal["State"] == "florida", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "florida", "Name of reporting district"].str.replace("orange county school board$", "orange county school district")
fiscal.ix[fiscal["State"] == "florida", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "florida", "Name of reporting district"].str.replace("orange county public schools$", "orange county school district")
fiscal.ix[fiscal["State"] == "maryland", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "maryland", "Name of reporting district"].str.replace("prince georges county public schools$", "prince george's county public schools")

fiscal
fiscal.to_csv("checking.csv", inplace = True)

In [170]:
# result.set_index(["Name of reporting district", "Year"], inplace = True)
# appended.set_index(["Name of reporting district", "Year"], inplace = True)

# Merge Fiscal and Appended

In [190]:
#merge mathread_summary with fiscal expenditure for summary stats 
list = ['State', 'Name of reporting district', 'Year']

summary_stats = pd.merge(mathread, fiscal, left_on = list, right_on = list)

drop_col = ['Instructional-related current expenditures', 'Total expenditures', 'Federal revenues', 'State revenues', 'Local revenues']
summary_stats.drop(drop_col, axis=1, inplace=True)
summary_stats["Name of reporting district"] = summary_stats["Name of reporting district"].str.capitalize()
summary_stats["State"] = summary_stats["State"].str.capitalize()
summary_stats.index.name = 'No.'

#renaming column headers
summary_stats.columns = summary_stats.columns.str.replace('numvalid', 'Number of Students')
summary_stats.columns = summary_stats.columns.str.replace('pctprof', '% Performance')
summary_stats.columns = summary_stats.columns.str.replace('_MTH', ' Math, ')
summary_stats.columns = summary_stats.columns.str.replace('_RLA', ' Reading, ')
summary_stats.columns = summary_stats.columns.str.replace('ALL', 'All Students,')
summary_stats.columns = summary_stats.columns.str.replace('00', 'All Grades,')
summary_stats.columns = summary_stats.columns.str.replace('01', 'Grade 1, ')
summary_stats.columns = summary_stats.columns.str.replace('02', 'Grade 2, ')
summary_stats.columns = summary_stats.columns.str.replace('03', 'Grade 3, ')
summary_stats.columns = summary_stats.columns.str.replace('04', 'Grade 4, ')
summary_stats.columns = summary_stats.columns.str.replace('05', 'Grade 5, ')
summary_stats.columns = summary_stats.columns.str.replace('06', 'Grade 6, ')
summary_stats.columns = summary_stats.columns.str.replace('07', 'Grade 7, ')
summary_stats.columns = summary_stats.columns.str.replace('08', 'Grade 8, ')

summary_stats.to_csv("merge_summary.csv", inplace = True)
mathread_summary.to_csv("mathread_sum.csv", inplace = True)

In [189]:
summary_stats

,State,DISTRICT_ID,Name of reporting district,"All Students, Math, All Grades,Number of Students","All Students, Math, All Grades,% Performance","MAM Math, All Grades,Number of Students","MAM Math, All Grades,% Performance","MAS Math, All Grades,Number of Students","MAS Math, All Grades,% Performance","MBL Math, All Grades,Number of Students",...,"MIG Reading, Grade 7, % Performance","MIG Reading, Grade 8, Number of Students","MIG Reading, Grade 8, % Performance","MIG Reading, HSNumber of Students","MIG Reading, HS% Performance",Total students,Total revenues,Current expenditures,Current expenditures per pupil,Total expenditures per pupil
No.,,,,,,,,,,,,,,,,,,,,,
0,Alaska,200180,Anchorage school district,28943,70,2464.0,54,4002.0,63,1810.0,...,70-74,136.0,65-69,250.0,70-74,48857,650738,611450,12515.1,14192.7
1,Arizona,404970,Mesa unified school district,36171,77,1536.0,60,934.0,86,1643.0,...,NaN,10.0,NaN,11.0,NaN,73044,635243,542481,7426.77,8257.3
2,Arizona,408800,Tucson unified school district,29411,62,1338.0,49,790.0,76,2173.0,...,NaN,0.0,NaN,0.0,NaN,59327,545561,471360,7945.12,9650.87
3,California,607440,Capistrano unified school district,28531,69,151.0,60-64,2424.0,85,521.0,...,NaN,8.0,NaN,11.0,NaN,52390,453589,417759,7974.02,8574.8
4,California,612330,Elk grove unified school district,33311,58,263.0,40-44,9724.0,70,6570.0,...,NaN,7.0,NaN,3.0,NaN,62294,596705,532880,8554.27,9532.04
5,California,614550,Fresno unified school district,39356,44,300.0,35-39,5544.0,54,4174.0,...,21,458.0,17,331.0,18,76460,838633,768663,10053.1,11334
6,California,614880,Garden grove unified school district,26538,60,53.0,50-59,8726.0,82,253.0,...,NaN,NaN,NaN,NaN,NaN,48669,468369,456637,9382.5,9657.15
7,California,622500,Long beach unified school district,46647,54,120.0,50-54,6284.0,70,8044.0,...,30-39,39.0,20-29,34.0,30-39,88186,914366,850615,9645.69,10454.5
8,California,622710,Los angeles unified school district,360812,44,1160.0,46,23593.0,75,38474.0,...,35-39,192.0,35-39,87.0,30-34,693680,9551053,7878168,11357.1,14767.8
9,California,633840,Sacramento city unified school district,25425,53,304.0,46,5857.0,65,5373.0,...,NaN,14.0,NaN,14.0,NaN,48446,545693,486908,10050.5,11559.1
10,California,634170,San bernardino city unified school district,28875,38,210.0,35-39,830.0,57,4542.0,...,NaN,NaN,NaN,NaN,NaN,56727,797791,553930,9764.84,12080.1
11,California,634410,San francisco unified school district,27588,59,166.0,40-44,13831.0,75,3235.0,...,NaN,27.0,40-59,21.0,NaN,55069,668282,534762,9710.76,13507.5
12,California,634620,San juan unified school district,24411,57,512.0,51,1808.0,72,1973.0,...,NaN,NaN,NaN,NaN,NaN,47400,480125,433280,9140.93,10066.8
13,California,635310,Santa ana unified school district,30415,47,24.0,21-39,932.0,75,211.0,...,25-29,118.0,20-24,117.0,25-29,57061,564867,544084,9535.13,10419.6
14,Florida,1200150,Brevard county school district,43225,77,136.0,80-84,896.0,89,6139.0,...,NaN,0.0,NaN,0.0,NaN,74369,747371,627018,8431.17,11901.5
15,Florida,1200180,Broward county school district,154311,71,322.0,75,5374.0,88,57526.0,...,NaN,15.0,NaN,19.0,NaN,258893,2874695,2339595,9036.92,11568.8
16,Florida,1200480,Duval county school district,71513,62,122.0,70-74,3001.0,82,31630.0,...,NaN,0.0,NaN,0.0,NaN,124740,1238175,1079389,8653.11,10034.4
17,Florida,1200870,Hillsborough county school district,115473,66,304.0,77,3565.0,87,24789.0,...,40-44,136.0,15-19,223.0,14-Oct,193180,2068665,1613384,8351.71,10936.1
18,Florida,1201080,Lee county school district,46088,66,165.0,70-74,754.0,84,6537.0,...,30-39,42.0,19-Nov,66.0,6-Sep,80541,980391,701153,8705.54,11745.2
19,Florida,1201440,Orange county school district,103093,64,426.0,73,4609.0,84,27840.0,...,21-39,24.0,NaN,41.0,20-29,174142,1974283,1524737,8755.71,11668.3
20,Florida,1201470,Osceola county school district,31184,58,88.0,60-64,806.0,75,3351.0,...,NaN,2.0,NaN,4.0,NaN,52742,628244,450830,8547.84,10427
21,Florida,1201500,Palm beach county school district,102749,70,482.0,76,2728.0,89,29304.0,...,40-44,187.0,25-29,344.0,18,170883,2183132,1605194,9393.53,13605.1
22,Florida,1201560,Pinellas county school district,62622,66,186.0,65-69,2361.0,81,11514.0,...,NaN,0.0,NaN,0.0,NaN,107892,1211026,966587,8958.84,10433
23,Florida,1201590,Polk county school district,55573,60,147.0,65-69,790.0,81,12120.0,...,40-44,79.0,35-39,95.0,15-19,93980,1250657,1017453,10826.3,12750.8
24,Florida,1201710,Seminole county school district,39911,77,96.0,75-79,1494.0,91,5283.0,...,NaN,0.0,NaN,0.0,NaN,65378,633500,529379,8097.2,9587.12
25,Florida,1201920,Volusia county school district,38193,64,81.0,60-64,621.0,84,5478.0,...,40-59,13.0,NaN,38.0,19-Nov,64488,713726,564674,8756.26,11605.4
26,Georgia,1300120,Atlanta public schools,24028,73,9.0,NaN,169.0,NaN,20068.0,...,NaN,NaN,NaN,NaN,NaN,49991,869896,675668,13515.8,15459.9
27,Georgia,1301230,Clayton county school district,25509,71,20.0,NaN,1131.0,89,18786.0,...,NaN,NaN,NaN,NaN,NaN,52717,567961,485152,9202.95,10298.5
28,Georgia,1301290,Cobb county school district,55700,85,119.0,80-84,2574.0,96,17376.0,...,NaN,3.0,NaN,1.0,NaN,107307,1157791,1011702,9428.11,10722.2
29,Georgia,1301740,Dekalb county school district,49802,71,52.0,60-69,1963.0,78,37266.0,...,NaN,NaN,NaN,NaN,NaN,100273,1245461,1059607,10567.2,11640.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,North carolina,3701920,Guilford county schools,38686,82,227.0,75-79,2118.0,85,15867.0,...,NaN,NaN,NaN,NaN,NaN,73205,795228,635691,8683.71,10311.2
241,North carolina,3702970,Charlotte-mecklenburg schools,73560,83,377.0,81,3574.0,91,31149.0,...,NaN,NaN,NaN,1.0,NaN,135954,1378746,1094447,8050.13,9781.83
242,North carolina,3704720,Wake county schools,78361,87,274.0,85-89,4979.0,96,19720.0,...,NaN,NaN,NaN,NaN,NaN,144173,1183308,1112138,7713.91,9273.33
243,Ohio,3904380,Columbus city school district,25602,54,55.0,60-69,579.0,67,14848.0,...,NaN,5.0,NaN,7.0,NaN,51134,980035,726788,14213.4,17917.1
244,Pennsylvania,4218990,Philadelphia school district,75193,49,109.0,55-59,5612.0,79,42657.0,...,NaN,15.0,NaN,47.0,19-Nov,166233,2896799,1934404,11636.7,18907.1
245,South carolina,4502310,Greenville county school district,37943,74,41.0,70-79,920.0,90,8715.0,...,NaN,NaN,NaN,NaN,NaN,71930,701103,540531,7514.68,9119.7
246,Tennessee,4702220,Knox county school district,30081,52,113.0,45-49,703.0,78,4657.0,...,NaN,NaN,NaN,NaN,NaN,57977,480087,440035,7589.82,8239.92
247,Tennessee,4703810,Shelby county school district,24551,58,71.0,50-54,1267.0,80,9544.0,...,NaN,NaN,NaN,NaN,NaN,47706,398743,377698,7917.2,9350.17
248,Texas,4807710,Aldine independent school district,31450,82,24.0,NaN,429.0,96,8351.0,...,NaN,4.0,NaN,5.0,NaN,63154,603132,536703,8498.32,9908.22
249,Texas,4808700,Arlington independent school district,32139,79,154.0,75-79,2180.0,93,7563.0,...,NaN,NaN,NaN,1.0,NaN,64484,591620,501627,7779.09,8966.07
250,Texas,4808940,Austin independent school district,41467,84,105.0,80-84,1301.0,91,3750.0,...,NaN,2.0,NaN,1.0,NaN,85697,1096563,808287,9431.92,12368.7
251,Texas,4811680,Brownsville independent school district,23986,81,4.0,NaN,72.0,NaN,21.0,...,70-74,129.0,75-79,103.0,80-84,49879,504356,472744,9477.82,10748.4
252,Texas,4815000,Conroe independent school district,27326,91,142.0,85-89,917.0,96,1653.0,...,NaN,3.0,NaN,1.0,NaN,51170,472852,375971,7347.49,10099.7
253,Texas,4816110,Cypress-fairbanks independent school district,56203,89,183.0,85-89,4597.0,97,9120.0,...,NaN,5.0,NaN,179.0,65-69,106097,953005,771525,7271.88,9270.54
254,Texas,4816230,Dallas independent school district,77597,74,262.0,75-79,981.0,71,18858.0,...,NaN,4.0,NaN,5.0,NaN,157162,1736994,1502681,9561.35,12987.2
255,Texas,4818300,El paso independent school district,31381,85,62.0,85-89,403.0,94,1286.0,...,60-69,56.0,60-69,59.0,70-79,64330,595870,533719,8296.58,9031.51
256,Texas,4819650,Fort bend independent school district,36613,88,140.0,85-89,8058.0,97,10964.0,...,NaN,NaN,NaN,NaN,NaN,68948,623356,521036,7556.94,9334.47
257,Texas,4819700,Fort worth independent school district,41456,75,72.0,75-79,699.0,74,9757.0,...,NaN,10.0,NaN,4.0,NaN,81651,835866,743459,9105.33,12610.9
258,Texas,4820340,Garland independent school district,29844,85,178.0,85-89,2408.0,95,5293.0,...,NaN,2.0,NaN,1.0,NaN,57833,545423,455996,7884.7,8673.35
259,Texas,4823640,Houston independent school district,95943,80,214.0,75-79,3140.0,94,24185.0,...,70-79,58.0,70-79,25.0,NaN,204245,2221585,1834882,8983.73,11243.8
260,Texas,4825170,Katy independent school district,32837,93,75.0,90-94,3664.0,NaN,3165.0,...,NaN,NaN,NaN,NaN,NaN,60803,599020,488484,8033.88,10544.2
261,Texas,4827300,Lewisville independent school district,27432,92,127.0,NaN,3018.0,95,2361.0,...,NaN,NaN,NaN,NaN,NaN,51484,547507,436883,8485.8,11215.7
262,Texas,4832940,North east independent school district,35247,85,92.0,85-89,1332.0,95,2594.0,...,NaN,10.0,NaN,4.0,NaN,66604,685916,559887,8406.21,10618.5
263,Texas,4834320,Pasadena independent school district,27197,83,69.0,85-89,745.0,95,1843.0,...,NaN,14.0,NaN,19.0,60-79,52218,506146,446410,8548.97,9159.06
264,Texas,4835100,Plano independent school district,29090,91,86.0,85-89,6023.0,98,3267.0,...,NaN,1.0,NaN,NaN,NaN,55568,633556,468456,8430.32,11914.1
265,Texas,4838730,San antonio independent school district,25902,71,14.0,NaN,59.0,70-79,1564.0,...,40-59,16.0,60-79,15.0,NaN,55116,578043,498348,9041.8,10375.1
266,Utah,4900030,Alpine school district,35503,84,174.0,70-74,860.0,82,288.0,...,NaN,NaN,NaN,NaN,NaN,67076,436619,359583,5360.83,6547.77
267,Utah,4900360,Granite school district,34475,59,501.0,48,2787.0,60,970.0,...,NaN,NaN,NaN,NaN,NaN,70083,474236,421152,6009.33,7648.47
268,Utah,4900420,Jordan school district,27767,77,113.0,55-59,930.0,76,282.0,...,NaN,NaN,NaN,NaN,NaN,50048,339004,276322,5521.14,6825.93
269,Wisconsin,5509600,Milwaukee school district,37025,20,303.0,23,1905.0,31,20802.0,...,NaN,6.0,NaN,5.0,NaN,80934,1310838,1152804,14243.8,16045.4

In [229]:
# result.set_index(["Name of reporting district", "Year"], inplace = True)

list = ['Name of reporting district', 'State', 'Year']

x = pd.merge(mathread, fiscal, left_on = list , right_on = list)

# pd.merge(result, appended, left_)

In [437]:
x.to_csv("x.csv", inplace = True)

In [357]:
x["State"] = pd.core.strings.str_strip(x["State"])

In [435]:
x

,Name of reporting district,State,Total students,Total revenues,Federal revenues,State revenues,Local revenues,Current expenditures,Instructional-related current expenditures,Current expenditures per pupil,...,MIG_MATH_GRADE05numvalid,MIG_MATH_GRADE05pctprof,MIG_MATH_GRADE06numvalid,MIG_MATH_GRADE06pctprof,MIG_MATH_GRADE07numvalid,MIG_MATH_GRADE07pctprof,MIG_MATH_GRADE08numvalid,MIG_MATH_GRADE08pctprof,MIG_MATH_GRADEHSnumvalid,MIG_MATH_GRADEHSpctprof
0,clark county school district,nevada,309051,3111868,196022,852790,2063056,2486063,1599505,8044.18,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,broward county school district,florida,258893,2874695,233523,1132545,1508627,2339595,1551639,9036.92,...,17.0,40-59,16.0,21-39,15.0,NaN,14.0,NaN,19.0,21-39
2,houston independent school district,texas,199534,2059689,267705,597926,1194058,1716764,1106808,8603.87,...,58.0,70-79,2.0,NaN,48.0,60-69,48.0,70-79,31.0,40-49
3,hillsborough county school district,florida,193180,2068665,247129,1034236,787300,1613384,1113859,8351.71,...,164.0,40-44,174.0,40-44,158.0,45-49,136.0,45-49,220.0,50-54
4,palm beach county school district,florida,170883,2183132,138401,494375,1550356,1605194,1106702,9393.53,...,200.0,45-49,209.0,45-49,185.0,45-49,186.0,55-59,340.0,60
5,dallas independent school district,texas,157804,1613014,216482,473768,922764,1457429,986852,9235.69,...,15.0,NaN,16.0,60-79,11.0,NaN,15.0,NaN,10.0,NaN
6,wake county schools,north carolina,133649,1264960,68546,691684,504730,1030073,695737,7707.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,charlotte-mecklenburg schools,north carolina,130979,1345133,105771,690492,548870,1062880,682134,8114.89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,duval county school district,florida,124740,1238175,106117,577864,554194,1079389,735878,8653.11,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
9,pinellas county school district,florida,107892,1211026,94072,454583,662371,966587,638052,8958.84,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
10,cypress-fairbanks independent school district,texas,96837,792371,43607,314951,433813,691201,474174,7137.78,...,0.0,NaN,2.0,NaN,1.0,NaN,0.0,NaN,0.0,NaN
11,polk county school district,florida,93980,1250657,82891,611812,555954,1017453,758602,10826.3,...,78.0,40-44,81.0,25-29,75.0,40-44,79.0,40-44,95.0,35-39
12,northside independent school district,texas,86260,766936,57934,318919,390083,673741,456378,7810.58,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
13,northside independent school district,texas,86260,766936,57934,318919,390083,673741,456378,7810.58,...,10.0,NaN,10.0,NaN,11.0,NaN,18.0,60-79,17.0,21-39
14,austin independent school district,texas,82564,970089,85664,231489,652936,745978,482385,9035.15,...,0.0,NaN,0.0,NaN,0.0,NaN,1.0,NaN,1.0,NaN
15,lee county school district,florida,80541,980391,67054,220143,693194,701153,440066,8705.54,...,44.0,20-29,46.0,30-39,45.0,20-29,42.0,20-29,65.0,45-49
16,fort worth independent school district,texas,78857,725234,96921,316310,312003,679641,434468,8618.65,...,8.0,NaN,3.0,NaN,5.0,NaN,4.0,NaN,5.0,NaN
17,brevard county school district,florida,74369,747371,51979,330491,364901,627018,436342,8431.17,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
18,guilford county schools,north carolina,70960,716338,67308,382482,266548,605653,388916,8535.13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,fort bend independent school district,texas,67992,571456,29488,252517,289451,519209,347217,7636.32,...,1.0,NaN,1.0,NaN,2.0,NaN,0.0,NaN,0.0,NaN
20,washoe county school district,nevada,65663,618949,45021,208833,365095,537291,344900,8182.55,...,3.0,NaN,1.0,NaN,1.0,NaN,1.0,NaN,3.0,NaN
21,seminole county school district,florida,65378,633500,40109,297872,295519,529379,357008,8097.2,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
22,volusia county school district,florida,64488,713726,51040,260755,401931,564674,374448,8756.26,...,34.0,50-59,33.0,20-29,23.0,40-59,13.0,NaN,38.0,40-49
23,north east independent school district,texas,62181,661970,33815,200974,427181,517876,354183,8328.52,...,3.0,NaN,5.0,NaN,2.0,NaN,3.0,NaN,3.0,NaN
24,el paso independent school district,texas,62123,583899,87626,314657,181616,535196,364400,8615.1,...,58.0,NaN,58.0,60-69,65.0,65-69,39.0,60-69,37.0,50-59
25,aldine independent school district,texas,60083,559919,68093,304002,187824,497157,314155,8274.5,...,5.0,NaN,2.0,NaN,6.0,NaN,4.0,NaN,4.0,NaN
26,garland independent school district,texas,57169,482310,38863,247658,195789,436329,290813,7632.27,...,0.0,NaN,2.0,NaN,2.0,NaN,1.0,NaN,1.0,NaN
27,san antonio independent school district,texas,54779,541408,91324,298733,151351,473536,314405,8644.48,...,21.0,NaN,25.0,60-79,29.0,60-79,27.0,60-79,21.0,40-59
28,knox county school district,tennessee,54490,487605,43208,147872,296525,429304,299791,7878.58,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,katy independent school district,texas,54402,508389,20328,218887,269174,413816,273788,7606.63,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,baltimore city public schools,maryland,83800,1441019,279303,892935,268781,1297470,848657,15482.9,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
139,lee county school district,florida,81967,827211,142228,193442,491541,736718,479548,8987.98,...,24.0,21-39,12.0,NaN,13.0,NaN,13.0,NaN,10.0,NaN
140,fort worth independent school district,texas,81651,835866,181849,301792,352225,743459,485333,9105.33,...,2.0,NaN,3.0,NaN,6.0,NaN,11.0,NaN,4.0,NaN
141,milwaukee school district,wisconsin,80934,1310838,265333,706087,339418,1152804,751839,14243.8,...,4.0,NaN,4.0,NaN,5.0,NaN,6.0,NaN,5.0,NaN
142,detroit city school district,michigan,77757,1250847,451471,561782,237594,1043177,666344,13415.9,...,1.0,NaN,NaN,NaN,1.0,NaN,2.0,NaN,NaN,NaN
143,anne arundel county public schools,maryland,75481,1102787,78339,360457,663991,982705,665968,13019.2,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
144,guilford county schools,north carolina,73205,795228,96060,350991,348177,635691,410035,8683.71,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
145,brevard county school district,florida,71866,665068,108726,283017,273325,586688,407927,8163.64,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
146,fort bend independent school district,texas,68948,623356,55659,222384,345313,521036,357687,7556.94,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147,north east independent school district,texas,66604,685916,74207,205551,406158,559887,380222,8406.21,...,4.0,NaN,3.0,NaN,4.0,NaN,10.0,NaN,3.0,NaN
148,arlington independent school district,texas,64484,591620,117878,207768,265974,501627,351488,7779.09,...,NaN,NaN,1.0,NaN,2.0,NaN,NaN,NaN,1.0,NaN
149,washoe county school district,nevada,64380,618416,71782,220100,326534,546408,340718,8487.23,...,2.0,NaN,1.0,NaN,1.0,NaN,2.0,NaN,1.0,NaN
150,el paso independent school district,texas,64330,595870,95837,308398,191635,533719,359722,8296.58,...,59.0,80-89,65.0,70-74,58.0,60-69,54.0,80-89,58.0,70-79
151,seminole county school district,florida,64229,577531,89063,246450,242018,526359,359026,8195.04,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
152,aldine independent school district,texas,63154,603132,116869,306953,179310,536703,355371,8498.32,...,7.0,NaN,8.0,NaN,8.0,NaN,4.0,NaN,5.0,NaN
153,volusia county school district,florida,61559,608890,104082,210594,294214,521732,345861,8475.32,...,17.0,40-59,10.0,NaN,6.0,NaN,8.0,NaN,7.0,NaN
154,katy independent school district,texas,60803,599020,56482,214508,328030,488484,328224,8033.88,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,garland independent school district,texas,57833,545423,93503,268384,183536,455996,309384,7884.7,...,1.0,NaN,NaN,NaN,1.0,NaN,2.0,NaN,1.0,NaN
156,plano independent school district,texas,55568,633556,56088,103322,474146,468456,330167,8430.32,...,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN
157,san antonio independent school district,texas,55116,578043,155469,262694,159880,498348,327175,9041.8,...,13.0,NaN,12.0,NaN,16.0,40-59,15.0,NaN,16.0,21-39
158,osceola county school district,florida,53357,509748,91019,231919,186810,446219,304461,8362.9,...,3.0,NaN,3.0,NaN,7.0,NaN,3.0,NaN,5.0,NaN
159,cumberland county schools,north carolina,53307,501648,89294,261340,151014,435393,299648,8167.65,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160,pasadena independent school district,texas,52218,506146,96482,263595,146069,446410,289679,8548.97,...,21.0,60-79,23.0,60-79,16.0,NaN,16.0,60-79,18.0,60-79
161,lewisville independent school district,texas,51484,547507,51783,145955,349769,436883,301123,8485.8,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
162,conroe independent school district,texas,51170,472852,52409,145180,275263,375971,249375,7347.49,...,2.0,NaN,3.0,NaN,3.0,NaN,3.0,NaN,1.0,NaN
163,columbus city school district,ohio,51134,980035,175203,346719,458113,726788,441681,14213.4,...,3.0,NaN,1.0,NaN,2.0,NaN,5.0,NaN,7.0,NaN
164,howard county public schools,maryland,50994,890726,39988,263585,587153,772020,547068,15139.4,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
165,brownsville independent school district,texas,49879,504356,117817,328668,57871,472744,315542,9477.82,...,103.0,80-84,113.0,65-69,117.0,65-69,130.0,65-69,101.0,65-69
166,atlanta public schools,georgia,49796,757348,103765,135631,517952,721187,386625,14482.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167,anchorage school district,alaska,49206,732488,114561,407204,210723,710465,448605,14438.6,...,254.0,65-69,233.0,65-69,266.0,50-54,214.0,55-59,377.0,54