# Mathread Merge

In [27]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from scipy import stats
import statsmodels.formula.api as sm

df1 = pd.read_csv("Math 08-09.csv")
df1['Year'] = np.array(2008)
df1.rename(columns = {"leanm08":"Name of reporting district"}, inplace=True)
df2 = pd.read_csv("Math 09-10.csv")
df2['Year'] = np.array(2009)
df2.rename(columns = {"leanm09":"Name of reporting district"}, inplace=True)
df3 = pd.read_csv("Math 10-11.csv")
df3['Year'] = np.array(2010)
df3.rename(columns = {"leanm10":"Name of reporting district"}, inplace=True)
df4 = pd.read_csv("Math 11-12.csv")
df4['Year'] = np.array(2011)
df4.rename(columns = {"leanm11":"Name of reporting district"}, inplace=True)
math = df1.append([df2, df3, df4])

read1 = pd.read_csv("Reading 08-09.csv")
read1['Year'] = np.array(2008)
read1.rename(columns = {"leanm08":"Name of reporting district"}, inplace=True)
read2 = pd.read_csv("Reading 09-10.csv")
read2['Year'] = np.array(2009)
read2.rename(columns = {"leanm09":"Name of reporting district"}, inplace=True)
read3 = pd.read_csv("Reading 10-11.csv")
read3['Year'] = np.array(2010)
read3.rename(columns = {"leanm10":"Name of reporting district"}, inplace=True)
read4 = pd.read_csv("Reading 11-12.csv")
read4['Year'] = np.array(2011)
read4.rename(columns = {"leanm11":"Name of reporting district"}, inplace=True)
read = read1.append([read2, read3, read4])

In [28]:
# merge math and reading performance indicators on Name of reporting district, State and Year 
list = ['LEAID', 'STNAM', 'Year']

mathread = pd.merge(math, read, left_on = list , right_on = list)

In [29]:
#header cleaning
mathread.rename(columns = {"STNAM": "State", "LEAID": "DISTRICT_ID", "Name of reporting district_x": 'Name of reporting district'}, inplace=True)
#mathread.columns = mathread.columns.str.replace('MTH', 'MATH_GRADE')
#mathread.columns = mathread.columns.str.replace('RLA', 'READ_GRADE')
mathread['State'] = mathread['State'].str.lower()
drop_col = ['FIPST_x', 'FIPST_y', 'Name of reporting district_y']
mathread.drop(drop_col, axis=1, inplace=True)
mathread['Name of reporting district'] = mathread['Name of reporting district'].str.lower()
mathread = mathread.replace('^[A-Z]{2}', np.nan, regex=True)
mathread = mathread.replace('-[0-9]{2}$', "", regex=True)
mathread = mathread.replace('[0-9]-[A-Za-z]{3}', np.nan, regex=True)
mathread = mathread.replace('n/a', np.nan)

In [30]:
mathread['Name of reporting district'] = np.where(mathread['State'] == 'california', 
                                                  mathread['Name of reporting district'].astype(str)+ str(' school district'), 
                                                  mathread['Name of reporting district'])

mathread['Name of reporting district'] = np.where(mathread['State'] == 'alabama', 
                                                  mathread['Name of reporting district'].astype(str)+ str(' school district'), 
                                                  mathread['Name of reporting district'])

mathread['Name of reporting district'] = np.where(mathread['State'] == 'florida', mathread['Name of reporting district'].astype(str)+ str(' county school district'), mathread['Name of reporting district'])


mathread["State"] = pd.core.strings.str_strip(mathread["State"])

In [31]:
mathread.ix[mathread["State"] == "illinois", "Name of reporting district"] = mathread.ix[mathread["State"] == "illinois", "Name of reporting district"].str.replace("sd", "school district")
mathread.ix[mathread["State"] == "pennsylvania", "Name of reporting district"] = mathread.ix[mathread["State"] == "pennsylvania", "Name of reporting district"].str.replace("city sd", "school district")
#remove double statistic
mathread.ix[mathread["State"] == "texas", "Name of reporting district"] = mathread.ix[mathread["State"] == "texas", "Name of reporting district"].str.replace("northside", "ns")
mathread.ix[mathread["State"] == "south carolina", "Name of reporting district"] = mathread.ix[mathread["State"] == "south carolina", "Name of reporting district"].str.replace("greenville 01", "greenville county school district")
mathread.ix[mathread["State"] == "tennessee", "Name of reporting district"] = mathread.ix[mathread["State"] == "tennessee", "Name of reporting district"].str.replace("memphis city schools district$", "memphis city schools")
mathread.ix[mathread["State"] == "arizona", "Name of reporting district"] = mathread.ix[mathread["State"] == "arizona", "Name of reporting district"].str.replace("district", "school district")
mathread.ix[mathread["State"] == "utah", "Name of reporting district"] = mathread.ix[mathread["State"] == "utah", "Name of reporting district"].str.replace("district", "school district")
mathread.ix[mathread["State"] == "georgia", "Name of reporting district"] = mathread.ix[mathread["State"] == "georgia", "Name of reporting district"].str.replace("county", "county school district")
mathread.ix[mathread["State"] == "alabama", "Name of reporting district"] = mathread.ix[mathread["State"] == "alabama", "Name of reporting district"].str.replace("county", "county school district")
mathread.ix[mathread["State"] == "tennessee", "Name of reporting district"] = mathread.ix[mathread["State"] == "tennessee", "Name of reporting district"].str.replace("knox county$", "knox county school district")
mathread.ix[mathread["State"] == "ohio", "Name of reporting district"] = mathread.ix[mathread["State"] == "ohio", "Name of reporting district"].str.replace("columbus city$", "columbus city school district")
mathread.ix[mathread["State"] == "tennessee", "Name of reporting district"] = mathread.ix[mathread["State"] == "tennessee", "Name of reporting district"].str.replace("shelby county$", "shelby county school district")

In [32]:
mathread.to_csv("mathread.csv", inplace = True)

# Append Fiscal Expenditure 08-11

In [33]:
df08 = pd.read_excel('100LSD_Fiscal_Tables_FY08.xlsx', header=2)
df09 = pd.read_excel('100LSD_Fiscal_Tables_FY09.xlsx', header=2)
df10 = pd.read_excel('100LSD_Fiscal_Tables_FY10.xlsx', header=2)
df11 = pd.read_excel('100LSD_Fiscal_Tables_FY11.xlsx', header=2)

In [34]:
df08.dropna(inplace = True)
df09.dropna(inplace = True)
df10.dropna(inplace = True)
df11.dropna(inplace = True)

In [35]:
df10_nospace = pd.core.strings.str_strip(df10['Name of reporting district'])
df11_nospace = pd.core.strings.str_strip(df11['Name of reporting district'])

In [36]:
df08['Year'] = np.array(2008)
df09['Year'] = np.array(2009)
df10['Year'] = np.array(2010)
df11['Year'] = np.array(2011)

In [37]:
df10.drop('Name of reporting district', axis=1, inplace=True)
df10['Name of reporting district'] = df10_nospace
df11.drop('Name of reporting district', axis=1, inplace=True)
df11['Name of reporting district'] = df11_nospace

In [38]:
cols = df10.columns.tolist()
col2 = cols[-1:] + cols[:-1]
df10 = df10[col2]
df11 = df11[col2]

In [39]:
fiscal = df08.append([df09, df10, df11])
fiscal['Name of reporting district'] = fiscal['Name of reporting district'].str.lower()
fiscal["Year"] = fiscal["Year"].astype(int)
fiscal["State"] = pd.core.strings.str_strip(fiscal["State"])
fiscal['State'] = fiscal['State'].str.lower()

In [40]:
#stripping arizona 
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 1') 
#stripping texas
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 901') 
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 902') 
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 903') 
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 904')
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 905')
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 906') 
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 907') 
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 908')
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 909')
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 910')
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 911') 
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 912') 
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 913') 
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 914') 
fiscal["Name of reporting district"] = fiscal["Name of reporting district"].str.strip(to_strip=' 915')

fiscal.ix[fiscal["State"] == "new mexico", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "new mexico", "Name of reporting district"].str.replace("school district", "public schools")
fiscal.ix[fiscal["State"] == "maryland", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "maryland", "Name of reporting district"].str.replace("county schools", "county public schools")
fiscal.ix[fiscal["State"] == "texas", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "texas", "Name of reporting district"].str.replace("arlington independent school$", "arlington independent school district")
fiscal.ix[fiscal["State"] == "maryland", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "maryland", "Name of reporting district"].str.replace("baltimore city schools$", "baltimore city public schools")
fiscal.ix[fiscal["State"] == "ohio", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "ohio", "Name of reporting district"].str.replace("columbus city$", "columbus city school district")
fiscal.ix[fiscal["State"] == "north carolina", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "north carolina", "Name of reporting district"].str.replace("cumberland county school$", "cumberland county schools")
fiscal.ix[fiscal["State"] == "michigan", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "michigan", "Name of reporting district"].str.replace("detroit public school district$", "detroit city school district")
fiscal.ix[fiscal["State"] == "georgia", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "georgia", "Name of reporting district"].str.replace("fulton county$", "fulton county school district")
fiscal.ix[fiscal["State"] == "georgia", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "georgia", "Name of reporting district"].str.replace("fulton county³$", "fulton county school district")
fiscal.ix[fiscal["State"] == "california", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "california", "Name of reporting district"].str.replace("garden grove unified school dist$", "garden grove unified school district")
fiscal.ix[fiscal["State"] == "north carolina", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "north carolina", "Name of reporting district"].str.replace("guilford county school$", "guilford county schools")
fiscal.ix[fiscal["State"] == "hawaii", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "hawaii", "Name of reporting district"].str.replace("hawaii public schools$", "hawaii department of education")
fiscal.ix[fiscal["State"] == "wisconsin", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "wisconsin", "Name of reporting district"].str.replace("milwaukee city school district$", "milwaukee school district")
fiscal.ix[fiscal["State"] == "maryland", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "maryland", "Name of reporting district"].str.replace("montgomery county school$", "montgomery county public schools")
fiscal.ix[fiscal["State"] == "florida", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "florida", "Name of reporting district"].str.replace("orange county school board$", "orange county school district")
fiscal.ix[fiscal["State"] == "florida", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "florida", "Name of reporting district"].str.replace("orange county public schools$", "orange county school district")
fiscal.ix[fiscal["State"] == "maryland", "Name of reporting district"] = fiscal.ix[fiscal["State"] == "maryland", "Name of reporting district"].str.replace("prince georges county public schools$", "prince george's county public schools")

fiscal
fiscal.to_csv("checking.csv", inplace = True)

In [41]:
# result.set_index(["Name of reporting district", "Year"], inplace = True)
# appended.set_index(["Name of reporting district", "Year"], inplace = True)

# Merge Fiscal and Appended

In [42]:
#merge mathread_summary with fiscal expenditure for summary stats 
list = ['State', 'Name of reporting district', 'Year']

summary_stats = pd.merge(mathread, fiscal, left_on = list, right_on = list)

drop_col = ['Instructional-related current expenditures', 'Total expenditures', 'Federal revenues', 'State revenues', 'Local revenues']
summary_stats.drop(drop_col, axis=1, inplace=True)
summary_stats["Name of reporting district"] = summary_stats["Name of reporting district"].str.capitalize()
summary_stats["State"] = summary_stats["State"].str.capitalize()
summary_stats.index.name = 'No.'

#renaming column headers
summary_stats.columns = summary_stats.columns.str.replace('numvalid', 'Number of Students')
summary_stats.columns = summary_stats.columns.str.replace('pctprof', '% Performance')
summary_stats.columns = summary_stats.columns.str.replace('_MTH', ' Math, ')
summary_stats.columns = summary_stats.columns.str.replace('_RLA', ' Reading, ')
summary_stats.columns = summary_stats.columns.str.replace('ALL', 'All Students,')
summary_stats.columns = summary_stats.columns.str.replace('00', 'All Grades,')
summary_stats.columns = summary_stats.columns.str.replace('01', 'Grade 1, ')
summary_stats.columns = summary_stats.columns.str.replace('02', 'Grade 2, ')
summary_stats.columns = summary_stats.columns.str.replace('03', 'Grade 3, ')
summary_stats.columns = summary_stats.columns.str.replace('04', 'Grade 4, ')
summary_stats.columns = summary_stats.columns.str.replace('05', 'Grade 5, ')
summary_stats.columns = summary_stats.columns.str.replace('06', 'Grade 6, ')
summary_stats.columns = summary_stats.columns.str.replace('07', 'Grade 7, ')
summary_stats.columns = summary_stats.columns.str.replace('08', 'Grade 8, ')

summary_stats.to_csv("merge_summary.csv", inplace = True)

In [43]:
summary_stats

,State,DISTRICT_ID,Name of reporting district,"All Students, Math, All Grades,Number of Students","All Students, Math, All Grades,% Performance","MAM Math, All Grades,Number of Students","MAM Math, All Grades,% Performance","MAS Math, All Grades,Number of Students","MAS Math, All Grades,% Performance","MBL Math, All Grades,Number of Students",...,"MIG Reading, Grade 7, % Performance","MIG Reading, Grade 8, Number of Students","MIG Reading, Grade 8, % Performance","MIG Reading, HSNumber of Students","MIG Reading, HS% Performance",Total students,Total revenues,Current expenditures,Current expenditures per pupil,Total expenditures per pupil
No.,,,,,,,,,,,,,,,,,,,,,
0,Alaska,200180,Anchorage school district,28943,70,2464.0,54,4002.0,63,1810.0,...,70,136.0,65,250.0,70,48857,650738,611450,12515.1,14192.7
1,Arizona,404970,Mesa unified school district,36171,77,1536.0,60,934.0,86,1643.0,...,NaN,10.0,NaN,11.0,NaN,73044,635243,542481,7426.77,8257.3
2,Arizona,408800,Tucson unified school district,29411,62,1338.0,49,790.0,76,2173.0,...,NaN,0.0,NaN,0.0,NaN,59327,545561,471360,7945.12,9650.87
3,California,607440,Capistrano unified school district,28531,69,151.0,60,2424.0,85,521.0,...,NaN,8.0,NaN,11.0,NaN,52390,453589,417759,7974.02,8574.8
4,California,612330,Elk grove unified school district,33311,58,263.0,40,9724.0,70,6570.0,...,NaN,7.0,NaN,3.0,NaN,62294,596705,532880,8554.27,9532.04
5,California,614550,Fresno unified school district,39356,44,300.0,35,5544.0,54,4174.0,...,21,458.0,17,331.0,18,76460,838633,768663,10053.1,11334
6,California,614880,Garden grove unified school district,26538,60,53.0,50,8726.0,82,253.0,...,NaN,NaN,NaN,NaN,NaN,48669,468369,456637,9382.5,9657.15
7,California,622500,Long beach unified school district,46647,54,120.0,50,6284.0,70,8044.0,...,30,39.0,20,34.0,30,88186,914366,850615,9645.69,10454.5
8,California,622710,Los angeles unified school district,360812,44,1160.0,46,23593.0,75,38474.0,...,35,192.0,35,87.0,30,693680,9551053,7878168,11357.1,14767.8
9,California,633840,Sacramento city unified school district,25425,53,304.0,46,5857.0,65,5373.0,...,NaN,14.0,NaN,14.0,NaN,48446,545693,486908,10050.5,11559.1
10,California,634170,San bernardino city unified school district,28875,38,210.0,35,830.0,57,4542.0,...,NaN,NaN,NaN,NaN,NaN,56727,797791,553930,9764.84,12080.1
11,California,634410,San francisco unified school district,27588,59,166.0,40,13831.0,75,3235.0,...,NaN,27.0,40,21.0,NaN,55069,668282,534762,9710.76,13507.5
12,California,634620,San juan unified school district,24411,57,512.0,51,1808.0,72,1973.0,...,NaN,NaN,NaN,NaN,NaN,47400,480125,433280,9140.93,10066.8
13,California,635310,Santa ana unified school district,30415,47,24.0,21,932.0,75,211.0,...,25,118.0,20,117.0,25,57061,564867,544084,9535.13,10419.6
14,Florida,1200150,Brevard county school district,43225,77,136.0,80,896.0,89,6139.0,...,NaN,0.0,NaN,0.0,NaN,74369,747371,627018,8431.17,11901.5
15,Florida,1200180,Broward county school district,154311,71,322.0,75,5374.0,88,57526.0,...,NaN,15.0,NaN,19.0,NaN,258893,2874695,2339595,9036.92,11568.8
16,Florida,1200480,Duval county school district,71513,62,122.0,70,3001.0,82,31630.0,...,NaN,0.0,NaN,0.0,NaN,124740,1238175,1079389,8653.11,10034.4
17,Florida,1200870,Hillsborough county school district,115473,66,304.0,77,3565.0,87,24789.0,...,40,136.0,15,223.0,NaN,193180,2068665,1613384,8351.71,10936.1
18,Florida,1201080,Lee county school district,46088,66,165.0,70,754.0,84,6537.0,...,30,42.0,NaN,66.0,NaN,80541,980391,701153,8705.54,11745.2
19,Florida,1201440,Orange county school district,103093,64,426.0,73,4609.0,84,27840.0,...,21,24.0,NaN,41.0,20,174142,1974283,1524737,8755.71,11668.3
20,Florida,1201470,Osceola county school district,31184,58,88.0,60,806.0,75,3351.0,...,NaN,2.0,NaN,4.0,NaN,52742,628244,450830,8547.84,10427
21,Florida,1201500,Palm beach county school district,102749,70,482.0,76,2728.0,89,29304.0,...,40,187.0,25,344.0,18,170883,2183132,1605194,9393.53,13605.1
22,Florida,1201560,Pinellas county school district,62622,66,186.0,65,2361.0,81,11514.0,...,NaN,0.0,NaN,0.0,NaN,107892,1211026,966587,8958.84,10433
23,Florida,1201590,Polk county school district,55573,60,147.0,65,790.0,81,12120.0,...,40,79.0,35,95.0,15,93980,1250657,1017453,10826.3,12750.8
24,Florida,1201710,Seminole county school district,39911,77,96.0,75,1494.0,91,5283.0,...,NaN,0.0,NaN,0.0,NaN,65378,633500,529379,8097.2,9587.12
25,Florida,1201920,Volusia county school district,38193,64,81.0,60,621.0,84,5478.0,...,40,13.0,NaN,38.0,NaN,64488,713726,564674,8756.26,11605.4
26,Georgia,1300120,Atlanta public schools,24028,73,9.0,NaN,169.0,NaN,20068.0,...,NaN,NaN,NaN,NaN,NaN,49991,869896,675668,13515.8,15459.9
27,Georgia,1301230,Clayton county school district,25509,71,20.0,NaN,1131.0,89,18786.0,...,NaN,NaN,NaN,NaN,NaN,52717,567961,485152,9202.95,10298.5
28,Georgia,1301290,Cobb county school district,55700,85,119.0,80,2574.0,96,17376.0,...,NaN,3.0,NaN,1.0,NaN,107307,1157791,1011702,9428.11,10722.2
29,Georgia,1301740,Dekalb county school district,49802,71,52.0,60,1963.0,78,37266.0,...,NaN,NaN,NaN,NaN,NaN,100273,1245461,1059607,10567.2,11640.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,North carolina,3701920,Guilford county schools,38686,82,227.0,75,2118.0,85,15867.0,...,NaN,NaN,NaN,NaN,NaN,73205,795228,635691,8683.71,10311.2
241,North carolina,3702970,Charlotte-mecklenburg schools,73560,83,377.0,81,3574.0,91,31149.0,...,NaN,NaN,NaN,1.0,NaN,135954,1378746,1094447,8050.13,9781.83
242,North carolina,3704720,Wake county schools,78361,87,274.0,85,4979.0,96,19720.0,...,NaN,NaN,NaN,NaN,NaN,144173,1183308,1112138,7713.91,9273.33
243,Ohio,3904380,Columbus city school district,25602,54,55.0,60,579.0,67,14848.0,...,NaN,5.0,NaN,7.0,NaN,51134,980035,726788,14213.4,17917.1
244,Pennsylvania,4218990,Philadelphia school district,75193,49,109.0,55,5612.0,79,42657.0,...,NaN,15.0,NaN,47.0,NaN,166233,2896799,1934404,11636.7,18907.1
245,South carolina,4502310,Greenville county school district,37943,74,41.0,70,920.0,90,8715.0,...,NaN,NaN,NaN,NaN,NaN,71930,701103,540531,7514.68,9119.7
246,Tennessee,4702220,Knox county school district,30081,52,113.0,45,703.0,78,4657.0,...,NaN,NaN,NaN,NaN,NaN,57977,480087,440035,7589.82,8239.92
247,Tennessee,4703810,Shelby county school district,24551,58,71.0,50,1267.0,80,9544.0,...,NaN,NaN,NaN,NaN,NaN,47706,398743,377698,7917.2,9350.17
248,Texas,4807710,Aldine independent school district,31450,82,24.0,NaN,429.0,96,8351.0,...,NaN,4.0,NaN,5.0,NaN,63154,603132,536703,8498.32,9908.22
249,Texas,4808700,Arlington independent school district,32139,79,154.0,75,2180.0,93,7563.0,...,NaN,NaN,NaN,1.0,NaN,64484,591620,501627,7779.09,8966.07
250,Texas,4808940,Austin independent school district,41467,84,105.0,80,1301.0,91,3750.0,...,NaN,2.0,NaN,1.0,NaN,85697,1096563,808287,9431.92,12368.7
251,Texas,4811680,Brownsville independent school district,23986,81,4.0,NaN,72.0,NaN,21.0,...,70,129.0,75,103.0,80,49879,504356,472744,9477.82,10748.4
252,Texas,4815000,Conroe independent school district,27326,91,142.0,85,917.0,96,1653.0,...,NaN,3.0,NaN,1.0,NaN,51170,472852,375971,7347.49,10099.7
253,Texas,4816110,Cypress-fairbanks independent school district,56203,89,183.0,85,4597.0,97,9120.0,...,NaN,5.0,NaN,179.0,65,106097,953005,771525,7271.88,9270.54
254,Texas,4816230,Dallas independent school district,77597,74,262.0,75,981.0,71,18858.0,...,NaN,4.0,NaN,5.0,NaN,157162,1736994,1502681,9561.35,12987.2
255,Texas,4818300,El paso independent school district,31381,85,62.0,85,403.0,94,1286.0,...,60,56.0,60,59.0,70,64330,595870,533719,8296.58,9031.51
256,Texas,4819650,Fort bend independent school district,36613,88,140.0,85,8058.0,97,10964.0,...,NaN,NaN,NaN,NaN,NaN,68948,623356,521036,7556.94,9334.47
257,Texas,4819700,Fort worth independent school district,41456,75,72.0,75,699.0,74,9757.0,...,NaN,10.0,NaN,4.0,NaN,81651,835866,743459,9105.33,12610.9
258,Texas,4820340,Garland independent school district,29844,85,178.0,85,2408.0,95,5293.0,...,NaN,2.0,NaN,1.0,NaN,57833,545423,455996,7884.7,8673.35
259,Texas,4823640,Houston independent school district,95943,80,214.0,75,3140.0,94,24185.0,...,70,58.0,70,25.0,NaN,204245,2221585,1834882,8983.73,11243.8
260,Texas,4825170,Katy independent school district,32837,93,75.0,90,3664.0,NaN,3165.0,...,NaN,NaN,NaN,NaN,NaN,60803,599020,488484,8033.88,10544.2
261,Texas,4827300,Lewisville independent school district,27432,92,127.0,NaN,3018.0,95,2361.0,...,NaN,NaN,NaN,NaN,NaN,51484,547507,436883,8485.8,11215.7
262,Texas,4832940,North east independent school district,35247,85,92.0,85,1332.0,95,2594.0,...,NaN,10.0,NaN,4.0,NaN,66604,685916,559887,8406.21,10618.5
263,Texas,4834320,Pasadena independent school district,27197,83,69.0,85,745.0,95,1843.0,...,NaN,14.0,NaN,19.0,60,52218,506146,446410,8548.97,9159.06
264,Texas,4835100,Plano independent school district,29090,91,86.0,85,6023.0,98,3267.0,...,NaN,1.0,NaN,NaN,NaN,55568,633556,468456,8430.32,11914.1
265,Texas,4838730,San antonio independent school district,25902,71,14.0,NaN,59.0,70,1564.0,...,40,16.0,60,15.0,NaN,55116,578043,498348,9041.8,10375.1
266,Utah,4900030,Alpine school district,35503,84,174.0,70,860.0,82,288.0,...,NaN,NaN,NaN,NaN,NaN,67076,436619,359583,5360.83,6547.77
267,Utah,4900360,Granite school district,34475,59,501.0,48,2787.0,60,970.0,...,NaN,NaN,NaN,NaN,NaN,70083,474236,421152,6009.33,7648.47
268,Utah,4900420,Jordan school district,27767,77,113.0,55,930.0,76,282.0,...,NaN,NaN,NaN,NaN,NaN,50048,339004,276322,5521.14,6825.93
269,Wisconsin,5509600,Milwaukee school district,37025,20,303.0,23,1905.0,31,20802.0,...,NaN,6.0,NaN,5.0,NaN,80934,1310838,1152804,14243.8,16045.4

In [44]:
# result.set_index(["Name of reporting district", "Year"], inplace = True)

list = ['Name of reporting district', 'State', 'Year']

x = pd.merge(mathread, fiscal, left_on = list , right_on = list)

# pd.merge(result, appended, left_)

In [45]:
x.to_csv("x.csv", inplace = True)

In [46]:
x["State"] = pd.core.strings.str_strip(x["State"])

In [47]:
x

,State,DISTRICT_ID,Name of reporting district,ALL_MTH00numvalid,ALL_MTH00pctprof,MAM_MTH00numvalid,MAM_MTH00pctprof,MAS_MTH00numvalid,MAS_MTH00pctprof,MBL_MTH00numvalid,...,Total students,Total revenues,Federal revenues,State revenues,Local revenues,Current expenditures,Instructional-related current expenditures,Current expenditures per pupil,Total expenditures,Total expenditures per pupil
0,alaska,200180,anchorage school district,28943,70,2464.0,54,4002.0,63,1810.0,...,48857,650738,61866,394410,194462,611450,390547,12515.1,693415,14192.7
1,arizona,404970,mesa unified school district,36171,77,1536.0,60,934.0,86,1643.0,...,73044,635243,55855,330173,249215,542481,344356,7426.77,603146,8257.3
2,arizona,408800,tucson unified school district,29411,62,1338.0,49,790.0,76,2173.0,...,59327,545561,63503,271967,210091,471360,264048,7945.12,572557,9650.87
3,california,607440,capistrano unified school district,28531,69,151.0,60,2424.0,85,521.0,...,52390,453589,23800,146857,282932,417759,291451,7974.02,449234,8574.8
4,california,612330,elk grove unified school district,33311,58,263.0,40,9724.0,70,6570.0,...,62294,596705,39960,396509,160236,532880,362820,8554.27,593789,9532.04
5,california,614550,fresno unified school district,39356,44,300.0,35,5544.0,54,4174.0,...,76460,838633,123361,590206,125066,768663,529797,10053.1,866597,11334
6,california,614880,garden grove unified school district,26538,60,53.0,50,8726.0,82,253.0,...,48669,468369,41967,321929,104473,456637,311884,9382.5,470004,9657.15
7,california,622500,long beach unified school district,46647,54,120.0,50,6284.0,70,8044.0,...,88186,914366,130977,660542,122847,850615,568479,9645.69,921942,10454.5
8,california,622710,los angeles unified school district,360812,44,1160.0,46,23593.0,75,38474.0,...,693680,9551053,1053853,6660389,1836811,7878168,5369564,11357.1,10244106,14767.8
9,california,633840,sacramento city unified school district,25425,53,304.0,46,5857.0,65,5373.0,...,48446,545693,78196,345913,121584,486908,322847,10050.5,559994,11559.1
10,california,634170,san bernardino city unified school district,28875,38,210.0,35,830.0,57,4542.0,...,56727,797791,73382,657628,66781,553930,363083,9764.84,685268,12080.1
11,california,634410,san francisco unified school district,27588,59,166.0,40,13831.0,75,3235.0,...,55069,668282,69870,258139,340273,534762,351320,9710.76,743842,13507.5
12,california,634620,san juan unified school district,24411,57,512.0,51,1808.0,72,1973.0,...,47400,480125,40410,303399,136316,433280,294438,9140.93,477164,10066.8
13,california,635310,santa ana unified school district,30415,47,24.0,21,932.0,75,211.0,...,57061,564867,69466,366775,128626,544084,374976,9535.13,594552,10419.6
14,florida,1200150,brevard county school district,43225,77,136.0,80,896.0,89,6139.0,...,74369,747371,51979,330491,364901,627018,436342,8431.17,885106,11901.5
15,florida,1200180,broward county school district,154311,71,322.0,75,5374.0,88,57526.0,...,258893,2874695,233523,1132545,1508627,2339595,1551639,9036.92,2995075,11568.8
16,florida,1200480,duval county school district,71513,62,122.0,70,3001.0,82,31630.0,...,124740,1238175,106117,577864,554194,1079389,735878,8653.11,1251694,10034.4
17,florida,1200870,hillsborough county school district,115473,66,304.0,77,3565.0,87,24789.0,...,193180,2068665,247129,1034236,787300,1613384,1113859,8351.71,2112627,10936.1
18,florida,1201080,lee county school district,46088,66,165.0,70,754.0,84,6537.0,...,80541,980391,67054,220143,693194,701153,440066,8705.54,945972,11745.2
19,florida,1201440,orange county school district,103093,64,426.0,73,4609.0,84,27840.0,...,174142,1974283,155268,726790,1092225,1524737,1042541,8755.71,2031946,11668.3
20,florida,1201470,osceola county school district,31184,58,88.0,60,806.0,75,3351.0,...,52742,628244,44158,320426,263660,450830,300320,8547.84,549940,10427
21,florida,1201500,palm beach county school district,102749,70,482.0,76,2728.0,89,29304.0,...,170883,2183132,138401,494375,1550356,1605194,1106702,9393.53,2324872,13605.1
22,florida,1201560,pinellas county school district,62622,66,186.0,65,2361.0,81,11514.0,...,107892,1211026,94072,454583,662371,966587,638052,8958.84,1125639,10433
23,florida,1201590,polk county school district,55573,60,147.0,65,790.0,81,12120.0,...,93980,1250657,82891,611812,555954,1017453,758602,10826.3,1198317,12750.8
24,florida,1201710,seminole county school district,39911,77,96.0,75,1494.0,91,5283.0,...,65378,633500,40109,297872,295519,529379,357008,8097.2,626787,9587.12
25,florida,1201920,volusia county school district,38193,64,81.0,60,621.0,84,5478.0,...,64488,713726,51040,260755,401931,564674,374448,8756.26,748410,11605.4
26,georgia,1300120,atlanta public schools,24028,73,9.0,NaN,169.0,NaN,20068.0,...,49991,869896,88718,162938,618240,675668,380854,13515.8,772858,15459.9
27,georgia,1301230,clayton county school district,25509,71,20.0,NaN,1131.0,89,18786.0,...,52717,567961,55651,264392,247918,485152,327128,9202.95,542904,10298.5
28,georgia,1301290,cobb county school district,55700,85,119.0,80,2574.0,96,17376.0,...,107307,1157791,66790,450898,640103,1011702,732211,9428.11,1150565,10722.2
29,georgia,1301740,dekalb county school district,49802,71,52.0,60,1963.0,78,37266.0,...,100273,1245461,83281,448301,713879,1059607,715201,10567.2,1167205,11640.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,north carolina,3701920,guilford county schools,38686,82,227.0,75,2118.0,85,15867.0,...,73205,795228,96060,350991,348177,635691,410035,8683.71,754828,10311.2
241,north carolina,3702970,charlotte-mecklenburg schools,73560,83,377.0,81,3574.0,91,31149.0,...,135954,1378746,179719,648832,550195,1094447,712880,8050.13,1329879,9781.83
242,north carolina,3704720,wake county schools,78361,87,274.0,85,4979.0,96,19720.0,...,144173,1183308,145597,678165,359546,1112138,760867,7713.91,1336964,9273.33
243,ohio,3904380,columbus city school district,25602,54,55.0,60,579.0,67,14848.0,...,51134,980035,175203,346719,458113,726788,441681,14213.4,916172,17917.1
244,pennsylvania,4218990,philadelphia school district,75193,49,109.0,55,5612.0,79,42657.0,...,166233,2896799,636770,1411582,848447,1934404,1182795,11636.7,3142979,18907.1
245,south carolina,4502310,greenville county school district,37943,74,41.0,70,920.0,90,8715.0,...,71930,701103,82614,325636,292853,540531,335854,7514.68,655980,9119.7
246,tennessee,4702220,knox county school district,30081,52,113.0,45,703.0,78,4657.0,...,57977,480087,58015,159097,262975,440035,302661,7589.82,477726,8239.92
247,tennessee,4703810,shelby county school district,24551,58,71.0,50,1267.0,80,9544.0,...,47706,398743,35054,180615,183074,377698,262062,7917.2,446059,9350.17
248,texas,4807710,aldine independent school district,31450,82,24.0,NaN,429.0,96,8351.0,...,63154,603132,116869,306953,179310,536703,355371,8498.32,625744,9908.22
249,texas,4808700,arlington independent school district,32139,79,154.0,75,2180.0,93,7563.0,...,64484,591620,117878,207768,265974,501627,351488,7779.09,578168,8966.07
250,texas,4808940,austin independent school district,41467,84,105.0,80,1301.0,91,3750.0,...,85697,1096563,155833,183304,757426,808287,528071,9431.92,1059959,12368.7
251,texas,4811680,brownsville independent school district,23986,81,4.0,NaN,72.0,NaN,21.0,...,49879,504356,117817,328668,57871,472744,315542,9477.82,536120,10748.4
252,texas,4815000,conroe independent school district,27326,91,142.0,85,917.0,96,1653.0,...,51170,472852,52409,145180,275263,375971,249375,7347.49,516802,10099.7
253,texas,4816110,cypress-fairbanks independent school district,56203,89,183.0,85,4597.0,97,9120.0,...,106097,953005,130329,340795,481881,771525,537599,7271.88,983577,9270.54
254,texas,4816230,dallas independent school district,77597,74,262.0,75,981.0,71,18858.0,...,157162,1736994,353634,448983,934377,1502681,974596,9561.35,2041088,12987.2
255,texas,4818300,el paso independent school district,31381,85,62.0,85,403.0,94,1286.0,...,64330,595870,95837,308398,191635,533719,359722,8296.58,580997,9031.51
256,texas,4819650,fort bend independent school district,36613,88,140.0,85,8058.0,97,10964.0,...,68948,623356,55659,222384,345313,521036,357687,7556.94,643593,9334.47
257,texas,4819700,fort worth independent school district,41456,75,72.0,75,699.0,74,9757.0,...,81651,835866,181849,301792,352225,743459,485333,9105.33,1029691,12610.9
258,texas,4820340,garland independent school district,29844,85,178.0,85,2408.0,95,5293.0,...,57833,545423,93503,268384,183536,455996,309384,7884.7,501606,8673.35
259,texas,4823640,houston independent school district,95943,80,214.0,75,3140.0,94,24185.0,...,204245,2221585,408408,532511,1280666,1834882,1208914,8983.73,2296500,11243.8
260,texas,4825170,katy independent school district,32837,93,75.0,90,3664.0,NaN,3165.0,...,60803,599020,56482,214508,328030,488484,328224,8033.88,641117,10544.2
261,texas,4827300,lewisville independent school district,27432,92,127.0,NaN,3018.0,95,2361.0,...,51484,547507,51783,145955,349769,436883,301123,8485.8,577430,11215.7
262,texas,4832940,north east independent school district,35247,85,92.0,85,1332.0,95,2594.0,...,66604,685916,74207,205551,406158,559887,380222,8406.21,707237,10618.5
263,texas,4834320,pasadena independent school district,27197,83,69.0,85,745.0,95,1843.0,...,52218,506146,96482,263595,146069,446410,289679,8548.97,478268,9159.06
264,texas,4835100,plano independent school district,29090,91,86.0,85,6023.0,98,3267.0,...,55568,633556,56088,103322,474146,468456,330167,8430.32,662042,11914.1
265,texas,4838730,san antonio independent school district,25902,71,14.0,NaN,59.0,70,1564.0,...,55116,578043,155469,262694,159880,498348,327175,9041.8,571832,10375.1
266,utah,4900030,alpine school district,35503,84,174.0,70,860.0,82,288.0,...,67076,436619,48206,238928,149485,359583,255935,5360.83,439198,6547.77
267,utah,4900360,granite school district,34475,59,501.0,48,2787.0,60,970.0,...,70083,474236,68178,243842,162216,421152,295161,6009.33,536028,7648.47
268,utah,4900420,jordan school district,27767,77,113.0,55,930.0,76,282.0,...,50048,339004,36432,174052,128520,276322,186589,5521.14,341624,6825.93
269,wisconsin,5509600,milwaukee school district,37025,20,303.0,23,1905.0,31,20802.0,...,80934,1310838,265333,706087,339418,1152804,751839,14243.8,1298621,16045.4